version: '3'
services:
  kaotonamae_back:
    restart: always
    build: ./golang
    tty: true
    volumes:
      - ./golang:/app
    working_dir: /app
    command: go run main.go
    ports:
      - "8080:8080"
    env_file:
      - ./mysql/.env

  kaotonamae_db:
    image: mysql:8.0
    restart: always
    ports:
      - 3312:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_database
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
